os: osx

env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

notifications:
  email: false
  slack:
    secure: "s5l7ljQQi5BS3AvcDbr13GS7QaRfIDSE0KzdZF9UVORTMIQJJxNAqllsGmj+CZtHieHC6Oo1/N55pW6fwu0t8KEUl7KJFP37a8NFfOsH0a6ZO64mdGQOors/MWVX7RNHPT7KrP3UaceXPXn01Wp7pLn0AOvE+BbUMcH2VTfWNWA21GDpuxltbKlpcHyrHOBl/bLgMsQv+Gu//pcmnww5jrL3t9lQ4eMYoW4t4JQBTgrkTiMdnDmJEkpp/UwEpI22gsRdn7OYR2TT38gmC49Kt3U0x+MW57D3vFS4FF2K4L4gvYhmNCZ1Bgg3Fr6wqi5U8NVn1wySFxwWog+g4jM/Eum8mqKrRQ14OQcrXiYGiQPJfMtdnB2w0un5WOg0WUweZtPu29dRr0IjV796SbHqjZf2mRrBbuanzogqS3SjF4jImmdZhyEGZ1RiUv66QZTzdg3Shjpe6j24rlQ7Pz1ip9/un3R/JaZj2Uzw6uOhy5D5Z+NC2IdMp6mdFZV03s8Q1FnNSzjJcAnmFYpldjauld6OOSV7IDkZnc836Um5XU9eusnWLcPNOEarBdF3V3HNqCsbmolXa90Xz9N133AErYkKgrQex7WPpIbkR7B+w+N1h921jdZhG5IyDeDepCm8gCn86h4Rgj/5PJeJFYyHKAQvSSl6NOTXzM651mqwPsY"

osx_image: xcode11.2

script:
  - swift package generate-xcodeproj
  - xcodebuild build test -project SwiftyParsers.xcodeproj -scheme SwiftyParsers-Package -destination 'platform=macOS,arch=x86_64' -enableCodeCoverage YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
