version: 2
jobs:
  macOS:
    macos:
      xcode: "10.1.0"
    steps:
      - checkout
      - run: swift build
      - run: swift test
  linux:
    docker:
      - image: apple/swift:4.2
    steps:
      - checkout
      - run: swift build
      - run: swift test
workflows:
   version: 2
     jobs:
       - macOS
       - linux
